name: Release

on:
  push:
    branches:
    - 'master'

jobs:

  Release_Drafter:
    name: Release_Drafter
    runs-on: ubuntu-latest
    steps:

    - name: Release Drafter
      # You may pin to the exact commit or the version.
      # uses: release-drafter/release-drafter@06d4616a80cd7c09ea3cf12214165ad6c1859e67
      id: create_release
      uses: release-drafter/release-drafter@v5.11.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: set upload_url
      id: set_upload_url
      uses: noobly314/share-data@v1
      with:
        share-id: release_url
        mode: set
        key: url
        value: ${{ steps.create_release.outputs.upload_url }}

  u-build:
    name: build
    needs: Release_Drafter
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
            
    - name: Build
      run: |
        ./lib_build
        ./aria2_build.sh
      
    - name: zip
      run: zip -q -r ubuntu.zip *
    
    - name: get upload_url
      id: get_upload_url
      uses: noobly314/share-data@v1
      with:
        share-id: release_url
        mode: get
        key: url

    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The URL for uploading assets to the release
        upload_url: ${{ steps.get_upload_url.outputs.data }}
        # The path to the asset you want to upload
        asset_path: ./ubuntu.zip
        # The name of the asset you want to upload
        asset_name: ubuntu.zip
        # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
        asset_content_type: application/zip

  w-build:
    name: build_windows
    needs: Release_Drafter
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        path-type: inherit
        update: true
        install: >-
          base-devel
          git

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: |
        ./lib_build
        rm -rf aria2_git
        git clone --depth=1 https://github.com/aria2/aria2.git aria2_git
        cp -rf ./patch/src ./aria2_git/
        cd aria2_git

        autoreconf -fi

        test -z "$HOST" && HOST=x86_64-w64-mingw32
        test -z "$PREFIX" && PREFIX=/usr/local/$HOST

        ./configure \
            --host=$HOST \
            --prefix=$PREFIX \
            --without-included-gettext \
            --disable-nls \
            --with-libcares \
            --without-gnutls \
            --without-wintls \
            --with-openssl \
            --with-sqlite3 \
            --without-libxml2 \
            --with-libexpat \
            --with-libz \
            --without-libgmp \
            --with-libssh2 \
            --without-libgcrypt \
            --without-libnettle \
            --with-cppunit-prefix=$PREFIX \
            ARIA2_STATIC=yes \
            CPPFLAGS="-I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib" \
            PKG_CONFIG="/usr/bin/pkg-config" \
            PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
            
        make
        cd ..
        cp aria2_git/src/aria2c ./aria2c.exe
        rm -rf aria2_git
        
    - name: zip
      run: .\7za.exe a -r .\windows.zip ./
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        path: ./windows.zip
